name: "My awesome tests"
outputDir: "marathon"
debug: false
filteringConfiguration:
  allowlist:
    # https://docs.marathonlabs.io/configuration/filtering#values-file-filtering
    - type: "fully-qualified-test-name"
      file: "smoke.filter"
vendorConfiguration:
  type: "Android"
  applicationApk: "../../dist/app-debug.apk"
  testApplicationApk: "../../dist/app-debug-androidTest.apk"
